// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLDrWofqLlS-tC2gT8wudXGkS8D3s91EQ',
    appId: '1:803825756441:web:8a9202908f811082a57d88',
    messagingSenderId: '803825756441',
    projectId: 'flipshopdata',
    authDomain: 'flipshopdata.firebaseapp.com',
    storageBucket: 'flipshopdata.appspot.com',
    measurementId: 'G-HQYR7BPB4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRPrISLfQ6X-rJwc8wAoH5In-B3H9PDSE',
    appId: '1:803825756441:android:c0770859042f3d06a57d88',
    messagingSenderId: '803825756441',
    projectId: 'flipshopdata',
    storageBucket: 'flipshopdata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0kCYyNzuD2XU46Yf9BFSXoi0U4OLSCE',
    appId: '1:803825756441:ios:8185e6f96189703aa57d88',
    messagingSenderId: '803825756441',
    projectId: 'flipshopdata',
    storageBucket: 'flipshopdata.appspot.com',
    iosBundleId: 'com.example.coffeeApp',
  );
}
